# Generated by Django 5.0.6 on 2024-07-13 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='est_ship_date',
            field=models.DateField(choices=[(datetime.date(2024, 7, 13), 'Today'), (datetime.date(2024, 7, 16), '3 Days After'), (datetime.date(2024, 7, 20), '7 Days After')], default=datetime.date(2024, 7, 13)),
        ),
    ]
