# Generated by Django 5.0.7 on 2024-07-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_alter_product_est_ship_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_type',
        ),
    ]
