# Generated by Django 5.0.7 on 2024-07-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_alter_product_est_ship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='est_ship_date',
            field=models.DateField(choices=[('in_stock', 'In Stock'), ('drop_ship', 'Drop Ship')], default='in_stock'),
        ),
    ]
