# Generated by Django 4.2.14 on 2024-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category_alter_product_est_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='est_ship_date',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('drop_ship', 'Drop Ship')], default='in_stock', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
